config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about', to: 'home#about'
  get '/contact', to: 'home#contact'
  get '/work', to: 'home#work'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  
  private
  
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def work
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_left_sidebar.html.slim
.panel
  p.text-center = image_tag 'headshot.jpg'
  p.text-center Ian Donovan . . . #{ t '.handsome_and_kind' }. #{ t '.good_man' }. #{ t '.and_his_code'}. #{ t '.Beautiful' }.
  .text-center
    a.button.dropdown href="#" data-dropdown="drop" aria-controls="drop" aria-expanded="false"
      | #{ t '.Translate_Page' }
    ul#drop.f-dropdown data-dropdown-content="true" aria-hidden="true" role="menu"
      li = link_to t('English'), locale: 'en'
      li = link_to t('French'), locale: 'fr'
      li = link_to t('Irish'), locale: 'ie'

app/views/home/about.html.slim
.row
  .medium-12.columns
    .medium-4.columns
      = render 'left_sidebar'
    .medium-8.columns
      .panel
        h2.text-center = t('About_Me')
        br
        p Put the tea on. We're about to get cozy.
        p
          | I was born and raised in New Jersey, where I eventually clawed my way out and went to Tufts University in Medford, Massachusetts, for college. It was a lot of fun: I ran for Student Senate during the spring semester of my senior year, #{ link_to 'winning a contested race', 'http://tuftsdaily.com/news/2012/02/02/thumbnail-optional-tcu-senate-update-three-students-walk-on-to-senate/', target: '_blank' }. I accrued tons of other marketable skills, too, like #{ link_to 'performing stand-up comedy ', 'http://tuftsdaily.com/news/2010/04/23/stand-up-comedy-collective-members-look-to-make-it-big/', target: '_blank' } (we lost horribly) and playing dodgeball. Oh, and I studied Computer Engineering, which I suppose was worth something. Please do not ask me to write assembly code ever again.
        p
          | I graduated in May of 2012, when I started working at #{ link_to 'Pubget', 'http://www.pubget.com', target: '_blank' }, a search engine for academic researchers. That's where I was introduced to Ruby on Rails, my current framework of choice. We used Solr, too, for a while, before shifting over to Elasticsearch. We were agile. Am I using enough buzzwords? Uhhhhh, synergy. Leverage. SaaS.
        p
          | In August of 2014, I moved to Carrboro, North Carolina, to live with my girlfriend. We have a cat named Henry. I work at #{ link_to 'Smashing Boxes', 'http://www.smashingboxes.com', target: '_blank' }, a tech consultancy in Durham, as a Backend Engineer. I'm brushing up on the frontend, too; this site (you're reading it!) is my first foray into #{ link_to 'Foundation', 'http://foundation.zurb.com/', target: '_blank' }, and I'm learning a bit of Angular in my free time.
        p
          | When I'm not working, I'm trying to hone some sort of skill, whether it's programming, learning a foreign language -- I'm #{ link_to 'on Duolingo', 'https://www.duolingo.com/anfeardathuil', target: '_blank' } -- or keeping dust off my drumset. I take the bus to and from work, so I have a lot of time to read. I have read Infinite Jest and I will absolutely mention it on my website in an attempt to impress you.
        p
          | If you have any questions, please #{ link_to 'just ask', contact_path }!
        p
          | In conclusion, here is a slideshow of animals I've met:
        .slideshow
          .slideshow-image
            = image_tag('henry_basket.jpg')
            .slideshow-caption.text-center Henry with his favorite basket
          .slideshow-image
            = image_tag('henry_standing_basket.jpg')
          .slideshow-image
            = image_tag('josie_kitchen.jpg')
            .slideshow-caption.text-center My family dog, Josie
          .slideshow-image
            = image_tag('josie_face.jpg')
          .slideshow-image
            = image_tag('chaucer.jpg')
            .slideshow-caption.text-center Chaucer
          .slideshow-image
            = image_tag('lola.jpg')
            .slideshow-caption.text-center Lola

app/views/home/contact.html.slim
.row
  .medium-12.columns
    .medium-4.columns
      = render 'left_sidebar'
    .medium-8.columns
      .panel
        h2.text-center = t('Contact')
        br
        p
          | #{ t('.As_a_citizen') }. #{ t('.Transcended') }. #{ t('.Accounts_list') }. #{ t('.Reachable') }. #{ t('.Synergize') }. #{ t('.We_can_be') } #{ link_to t('.thought_lords'), 'http://jonhendren.com/', target: "_blank" }.
        p.text-center
          a title="#{ t('.email') }" href="mailto:idonovan90(at)gmail(dot)com"
            i.fi-mail
          a title="#{ t('.my_job') }" href="http://www.smashingboxes.com/bio/ian-donovan/" target="_blank"
            i.fi-torso-business
          a title="Github" href="http://www.github.com/iandonovan/" target="_blank"
            i.fi-social-github
          a title="Linkedin" href="http://www.linkedin.com/pub/ian-donovan/60/475/88a/" target="_blank"
            i.fi-social-linkedin
          a title="Rdio" href="http://www.rdio.com/people/iandonovan/" target="_blank"
            i.fi-social-rdio
          a title="Last.fm" href="http://www.last.fm/user/papadonovan/" target="_blank"
            i.fi-social-lastfm

app/views/home/index.html.slim
.row
  .medium-12.columns
    .medium-4.columns
      = render 'left_sidebar'
    .medium-8.columns
      .panel
        h1.text-center = t('.Welcome')
        h4.subheader.text-center = t('.RailsTriangle')
        br
        p
          | #{ t '.Im_Ian' }, #{ t '.rails_dev'} #{ t '.living_in_carrboro' }. #{ t('.Feel_free') }, #{ t('.maybe') } #{ link_to t('.get_to_know_me'), about_path }, #{ link_to t('.introduce_yourself'), contact_path }, #{ t '.or' } #{ link_to t('.check_my_work'), work_path }. #{ t '.Thanks' }!
        p
          | #{ t('.if_youre_into_it') }, #{ t '.site_three_languages' }: #{ link_to t('English'), locale: 'en' }, #{ link_to t('French'), locale: 'fr' }, #{ t('.and') } #{ link_to t('Irish'), locale: 'ie' }. #{ t '.Irish_is_a_language' }. #{ t '.You_can' } #{ link_to t('.learn_duolingo'), 'https://www.duolingo.com/course/ga/en/Learn-Irish-Online', target: '_blank' }, #{ t '.though' }!

app/views/home/work.html.slim
.row
  .medium-12.columns
    .medium-4.columns
      = render 'left_sidebar'
    .medium-8.columns
      .panel
        h2.text-center = t('Projects')
        br
        .row
          .medium-8.columns
            p #{ link_to 'Sponsored Corgis', 'https://chrome.google.com/webstore/detail/sponsored-corgis/hhjaidjgkafhbemfmgmbkocjcnbbpbep?hl=en-US', target: '_blank' } is a Chrome extension I wrote to replace Facebook Newsfeed ads with pictures of corgis. It's #{ link_to 'open source', 'https://github.com/iandonovan/sponsored_corgis', target: '_blank' }, too.
          .medium-4.columns
            = link_to image_tag('corgi.jpg'), image_path('corgi.jpg'), target: '_blank', class: 'th'

        br
          .row
            .medium-8.columns
              p #{ link_to 'Brandify', 'https://github.com/iandonovan/brandify' } is a #{ link_to 'Rubygem', 'https://rubygems.org/gems/brandify' } to generate Twitter bios. This website is even using it. Watch. Reload the page and the text to the right will change:
            .medium-4.columns
              p #{ Brandify.bio }
        br
          .row
            .medium-8.columns
              p #{ link_to 'Hashcloud', 'https://github.com/iandonovan/hashcloud' } is a small Ruby script I wrote to create wordmaps for Twitter queries. Search for a term and the script compiles tweets and returns a hash, ready for your graphing library.
            
        br
        .row
          .medium-8.columns
            p This website is #{ link_to 'open source!', 'https://github.com/iandonovan/personal_brand', target: '_blank' } Isn't that something?
          .medium-4.columns
            = link_to image_tag('homepage_screenshot.png'), image_path('homepage_screenshot.png'), target: '_blank', class: 'th'

app/views/layouts/_topnav.html.slim
.icon-bar.four-up
  = link_to root_path, title: t("Home") do
    i.fi-home
  = link_to about_path, title: t("About_Me") do
    i.fi-info
  = link_to contact_path, title: t("Contact") do
    i.fi-address-book
  = link_to work_path, title: t("Projects") do
    i.fi-wrench  

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta content="Ian Donovan ruby rails durham raleigh developer" name="keywords"

    title = content_for?(:title) ? yield(:title) : "IanDonovan.com | Web Developer"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags

  body
    = render "layouts/topnav"
    = yield